name: Python CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Клонирование репозитория
      uses: actions/checkout@v3

    - name: Установка Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Проверка стиля кода (flake8)
      run: |
        pip install flake8
        flake8 .

    - name: Запуск тестов
      run: |
        pytest tests/ --html=report.html --self-contained-html

    - name: Загрузка отчёта (опционально)
      uses: actions/upload-artifact@v3
      with:
        name: html-report
        path: report.html
